/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.launcher.server;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import com.jme3.system.JmeContext;
import amara.engine.applications.masterserver.server.MasterserverServerApplication;
import amara.engine.network.MessagesSerializer;

/**
 *
 * @author Carl
 */
public class ServerLauncher extends javax.swing.JFrame{

    public ServerLauncher(){
        initComponents();
        MessagesSerializer.registerClasses();
        MasterserverServerApplication masterServer = new MasterserverServerApplication(33900);
        masterServer.start(JmeContext.Type.Headless);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amara - Server");

        jLabel1.setText("Clients: ?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]){
        Logger.getLogger("").setLevel(Level.SEVERE);
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception ex){
        }
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            @Override
            public void run(){
                new ServerLauncher().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
