package amara.applications.master.client.launcher.panels;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;
import javax.swing.border.LineBorder;
import amara.core.files.FileAssets;

public class PanAvatarSelection extends JPanel {

    public PanAvatarSelection(PanProfile panProfile) {
        initComponents();
        this.panProfile = panProfile;
        addAvatarButtons();
    }
    private static final String[] AVATARS = new String[] {
        "jmonkeyengine", "burning_cow", "horn", "firecracker", "branch", "rubber_duck",
        "guitar", "hearts", "hourglass", "spirit_wolf", "bull", "present",
        "ghost", "butterfly", "helmet", "golden_statue", "potion", "raven_artifact",
        "ether_wolf", "ether_shina", "ether_anna", "ether_demon1", "ether_yuki", "ether_amara"
    };
    private PanProfile panProfile;

    private void addAvatarButtons() {
        int x = 1;
        int y = 1;
        int buttonSize = 70;
        for (int i = 0; i < AVATARS.length; i++) {
            final String avatar = AVATARS[i];
            final JButton btnAvatar = new JButton(FileAssets.getImageIcon(getAvatarFilePath(avatar), buttonSize, buttonSize));
            btnAvatar.addActionListener(evt -> panProfile.changeAvatar(avatar));
            btnAvatar.addMouseListener(new MouseAdapter(){

                @Override
                public void mouseEntered(MouseEvent evt) {
                    super.mouseEntered(evt);
                    btnAvatar.setBorder(new LineBorder(Color.WHITE));
                }

                @Override
                public void mouseExited(MouseEvent evt) {
                    super.mouseExited(evt);
                    btnAvatar.setBorder(null);
                }
            });
            btnAvatar.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnAvatar.setLocation(x, y);
            btnAvatar.setSize(buttonSize, buttonSize);
            add(btnAvatar);
            x += buttonSize;
            if ((((i + 1) % 6) == 0)) {
                x = 1;
                y += buttonSize;
            }
        }
    }

    public static String getAvatarFilePath(String avatar) {
        return "Interface/client/avatars/" + avatar + ".png";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(30, 30, 30));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(422, 282));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
