/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.applications.master.client.launcher.panels;

import java.awt.Color;
import javax.swing.border.LineBorder;
import amara.applications.master.network.messages.objects.OwnedGameCharacter;
import amara.core.files.FileAssets;

/**
 *
 * @author Carl
 */
public class PanGameSelection_Character extends javax.swing.JPanel {

    public PanGameSelection_Character(PanGameSelection panGameSelection, OwnedGameCharacter ownedCharacter){
        initComponents();
        this.panGameSelection = panGameSelection;
        this.ownedCharacter = ownedCharacter;
        lblIcon.setIcon(FileAssets.getImageIcon("Interface/client/characters/" + ownedCharacter.getCharacter().getName() + "/icon_56.png"));
        updateBorder();
    }
    private Color BORDER_COLOR_ACTIVE = new Color(0, 90, 255);
    private Color BORDER_COLOR_NOT_ACTIVE = new Color(90, 90, 90);
    private PanGameSelection panGameSelection;
    private OwnedGameCharacter ownedCharacter;
    private boolean isHovered;
    
    public void updateBorder(){
        Color borderColor;
        if(isHovered || (ownedCharacter.getCharacter().getID() == panGameSelection.getSelectedCharacterID())){
            borderColor = BORDER_COLOR_ACTIVE;
        }
        else{
            borderColor = BORDER_COLOR_NOT_ACTIVE;
        }
        setBorder(new LineBorder(borderColor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();

        lblIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconMouseClicked
        panGameSelection.setSelectedCharacter(ownedCharacter);
        panGameSelection.sendGameSelectionPlayerDataUpdate();
    }//GEN-LAST:event_lblIconMouseClicked

    private void lblIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconMouseEntered
        isHovered = true;
        updateBorder();
    }//GEN-LAST:event_lblIconMouseEntered

    private void lblIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconMouseExited
        isHovered = false;
        updateBorder();
    }//GEN-LAST:event_lblIconMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcon;
    // End of variables declaration//GEN-END:variables
}
