/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.applications.master.client.launcher.panels;

import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import amara.applications.master.client.MasterserverClientUtil;
import amara.applications.master.client.launcher.comboboxes.ComboboxModel_MapSpells;
import amara.applications.master.network.messages.objects.*;
import amara.applications.ingame.shared.maps.MapSpell;
import amara.applications.ingame.shared.maps.MapSpells;
import amara.core.files.FileAssets;

/**
 *
 * @author Carl
 */
public class PanGameSelection_Player extends javax.swing.JPanel{

    public PanGameSelection_Player(PanGameSelection panGameSelection, GameSelectionPlayer player){
        initComponents();
        this.panGameSelection = panGameSelection;
        PlayerProfileData playerProfileData = PanLobby_Player.getLobbyPlayerProfile(player.getLobbyPlayer());
        lblPlayerName.setText(playerProfileData.getLogin());
        GameCharacter selectedCharacter = MasterserverClientUtil.getCharacter(player.getPlayerData().getCharacterID());
        if(selectedCharacter != null){
            lblCharacterIcon.setIcon(FileAssets.getImageIcon("Interface/client/characters/" + selectedCharacter.getName() + "/icon_56.png"));
        }
        //MapSpells
        if(player.getPlayerData().getMapSpellsIndices() != null){
            JLabel[] lblMapSpellIcons = new JLabel[]{lblMapSpellIcon1, lblMapSpellIcon2};
            MapSpells[] mapSpells = panGameSelection.getMap().getSpells();
            LinkedList<int[]> selectableMapSpellsIndices = panGameSelection.getSelectableMapSpellsIndices();
            for(int i=0;i<2;i++){
                if(i < selectableMapSpellsIndices.size()){
                    int groupIndex = selectableMapSpellsIndices.get(i)[0];
                    int selectedIndex = player.getPlayerData().getMapSpellsIndices()[groupIndex][i];
                    MapSpell mapSpell = mapSpells[groupIndex].getMapSpells()[selectedIndex];
                    ImageIcon icon = ComboboxModel_MapSpells.getMapSpellIcon(mapSpell, 30);
                    lblMapSpellIcons[i].setIcon(icon);
                }
            }
        }
    }
    private PanGameSelection panGameSelection;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCharacterIcon = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblMapSpellIcon2 = new javax.swing.JLabel();
        lblMapSpellIcon1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 55, 55));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 90)));

        lblCharacterIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 90)));
        lblCharacterIcon.setPreferredSize(new java.awt.Dimension(30, 30));

        lblPlayerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlayerName.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayerName.setText("???");
        lblPlayerName.setPreferredSize(new java.awt.Dimension(115, 30));

        lblMapSpellIcon2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 90)));
        lblMapSpellIcon2.setPreferredSize(new java.awt.Dimension(30, 30));

        lblMapSpellIcon1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 90, 90)));
        lblMapSpellIcon1.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblCharacterIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMapSpellIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMapSpellIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(lblPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMapSpellIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMapSpellIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCharacterIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCharacterIcon;
    private javax.swing.JLabel lblMapSpellIcon1;
    private javax.swing.JLabel lblMapSpellIcon2;
    private javax.swing.JLabel lblPlayerName;
    // End of variables declaration//GEN-END:variables
}
