/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.applications.master.client.launcher.panels;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import amara.applications.master.client.launcher.api.WebserverInfo;
import amara.applications.master.client.launcher.buttons.*;
import amara.applications.master.client.launcher.panels.loginscreens.SwingLoginScreen;
import amara.core.GameInfo;
import amara.core.Util;

/**
 *
 * @author Carl
 */
public class PanLogin_Swing extends PanLogin{

    public PanLogin_Swing(SwingLoginScreen loginScreen){
        initComponents();
        this.loginScreen = loginScreen;
        loginScreen.setSize(644, 372);
        JComponent btnLogin = ButtonUtil.addImageBackgroundButton(panContainer_btnLogin, new DefaultButtonBuilder("default_176x30", "Login"));
        btnLogin.addMouseListener(new MouseAdapter(){

            @Override
            public void mouseClicked(MouseEvent evt){
                super.mouseClicked(evt);
                login();
            }
        });
        lblTitle.setText(GameInfo.NAME);
        panBox.setBackground(new Color(255, 255, 255, 30));
        addTextFieldListeners();
        showIsLoading(false);
    }
    private SwingLoginScreen loginScreen;
    private Thread updateThread = new Thread(new Runnable(){

        @Override
        public void run(){
            long lastTimestamp = System.currentTimeMillis();
            float lastTimePerFrame;
            while(!stopUpdateThread){
                long currentTimestamp = System.currentTimeMillis();
                lastTimePerFrame = ((currentTimestamp - lastTimestamp) / 1000f);
                lastTimestamp = currentTimestamp;
                loginScreen.update(lastTimePerFrame);
                updateUI();
                Util.sleep(1000 / 60);
            }
            loginScreen.close();
        }
    });
    private boolean stopUpdateThread;
    
    private void addTextFieldListeners(){
        KeyAdapter loginTextFieldKeyListener = new KeyAdapter(){

            @Override
            public void keyPressed(KeyEvent evt){
                super.keyPressed(evt);
                switch(evt.getKeyCode()){
                    case KeyEvent.VK_ENTER:
                        login();
                        break;
                }
            }
        };
        txtLogin.addKeyListener(loginTextFieldKeyListener);
        txtPassword.addKeyListener(loginTextFieldKeyListener);
    }

    @Override
    public void paintComponent(Graphics _graphics){
        super.paintComponent(_graphics);
        Graphics2D graphics = (Graphics2D) _graphics;
        loginScreen.paint(graphics);
    }
    
    private void login(){
        String login = txtLogin.getText();
        String password = new String(txtPassword.getPassword());
        login(login, password);
    }
    
    @Override
    public void start(){
        updateThread.start();
    }
    
    @Override
    public void showIsLoading(boolean isLoading){
        pbrLoading.setVisible(isLoading);
    }

    @Override
    public void close(){
        super.close();
        stopUpdateThread = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBox = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        panContainer_btnLogin = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pbrLoading = new javax.swing.JProgressBar();

        panBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panBox.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setText("<html>No account? <u>Register</u></html>");
        lblRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panContainer_btnLoginLayout = new javax.swing.GroupLayout(panContainer_btnLogin);
        panContainer_btnLogin.setLayout(panContainer_btnLoginLayout);
        panContainer_btnLoginLayout.setHorizontalGroup(
            panContainer_btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panContainer_btnLoginLayout.setVerticalGroup(
            panContainer_btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panBoxLayout = new javax.swing.GroupLayout(panBox);
        panBox.setLayout(panBoxLayout);
        panBoxLayout.setHorizontalGroup(
            panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(panContainer_btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panBoxLayout.setVerticalGroup(
            panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panContainer_btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pbrLoading.setIndeterminate(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pbrLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(panBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbrLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        Util.browseURL(WebserverInfo.getWebserverURL("register.php", null).toExternalForm());
    }//GEN-LAST:event_lblRegisterMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panBox;
    private javax.swing.JPanel panContainer_btnLogin;
    private javax.swing.JProgressBar pbrLoading;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
