/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.applications.master.client.launcher.panels;

import java.awt.event.MouseEvent;
import javax.swing.JPanel;

/**
 *
 * @author Carl
 */
public class PanMainMenu extends javax.swing.JPanel{

    public PanMainMenu(){
        initComponents();
        initializePanels();
    }
    private PanProfile panProfile;
    private PanDebug panDebug;
    private boolean isDebugPanelVisible;
    
    private void initializePanels(){
        panHeaderContainer.add(new PanHeader());
        addPanelTab("Home", new PanHomeScreen());
        panProfile = new PanProfile();
        addPanelTab("Profile", panProfile);
        //addPanelTab("Items", new PanItems());
        addPanelTab("Play", new PanPlay(this));
        addPanelTab("Characters", new PanCharacters());
        addPanelTab("Settings", new PanSettings());
        addPanelTab("Thanks", new PanThanks());
        addPanelTab("Info", new PanInfo());
        panDebug = new PanDebug();
    }
    
    private void addPanelTab(String title, JPanel panel){
        tpaneContainer.add(title, panel);
    }
    
    public void setSelectedTab(int tabIndex){
        tpaneContainer.setSelectedIndex(tabIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panHeaderContainer = new javax.swing.JPanel();
        tpaneContainer = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(55, 55, 55));

        panHeaderContainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panHeaderContainerMousePressed(evt);
            }
        });
        panHeaderContainer.setLayout(new java.awt.GridLayout(1, 0));

        tpaneContainer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpaneContainerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpaneContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(panHeaderContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panHeaderContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpaneContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tpaneContainerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpaneContainerStateChanged
        if(tpaneContainer.getSelectedComponent() == panProfile){
            panProfile.resetToOwnProfile();
        }
    }//GEN-LAST:event_tpaneContainerStateChanged

    private void panHeaderContainerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panHeaderContainerMousePressed
        if(evt.getButton() == MouseEvent.BUTTON2){
            isDebugPanelVisible = (!isDebugPanelVisible);
            if(isDebugPanelVisible){
                addPanelTab("Debug", panDebug);
            }
            else{
                tpaneContainer.remove(panDebug);
            }
        }
    }//GEN-LAST:event_panHeaderContainerMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panHeaderContainer;
    private javax.swing.JTabbedPane tpaneContainer;
    // End of variables declaration//GEN-END:variables
}
