/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.applications.master.client.launcher.panels;

import amara.applications.master.network.messages.objects.*;

/**
 *
 * @author Carl
 */
public class PanGameSelection_Team extends javax.swing.JPanel{

    public PanGameSelection_Team(PanGameSelection panGameSelection, GameSelectionPlayer[] team){
        initComponents();
        this.panGameSelection = panGameSelection;
        int y = 0;
        int panelHeight = 70;
        for(GameSelectionPlayer player : team){
            if(PanLobby_Player.isOwnPlayer(player.getLobbyPlayer())){
                isOwnTeam = true;
            }
            PanGameSelection_Player panPlayer = new PanGameSelection_Player(panGameSelection, player);
            panPlayer.setLocation(0, y);
            panPlayer.setSize(180, panelHeight);
            panPlayersContainer.add(panPlayer);
            y += (panelHeight + 5);
        }
        lblTitle.setText((isOwnTeam?"Your":"Enemy") + " Team:");
    }
    private PanGameSelection panGameSelection;
    private boolean isOwnTeam;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        panPlayersContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(30, 30, 30));

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Team:");

        panPlayersContainer.setOpaque(false);

        javax.swing.GroupLayout panPlayersContainerLayout = new javax.swing.GroupLayout(panPlayersContainer);
        panPlayersContainer.setLayout(panPlayersContainerLayout);
        panPlayersContainerLayout.setHorizontalGroup(
            panPlayersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panPlayersContainerLayout.setVerticalGroup(
            panPlayersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(panPlayersContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPlayersContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panPlayersContainer;
    // End of variables declaration//GEN-END:variables
}
