/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.applications.master.client.launcher.panels;

import java.util.HashMap;
import amara.applications.master.client.MasterserverClientUtil;
import amara.applications.master.network.messages.*;
import amara.applications.master.network.messages.objects.*;
import amara.core.files.FileAssets;

/**
 *
 * @author Carl
 */
public class PanLobby_Player extends javax.swing.JPanel{

    public PanLobby_Player(PanLobby panLobby, LobbyPlayer lobbyPlayer){
        initComponents();
        this.panLobby = panLobby;
        this.lobbyPlayer = lobbyPlayer;
        PlayerProfileData playerProfileData = getLobbyPlayerProfile(lobbyPlayer);
        String avatarFilePath = PanAvatarSelection.getAvatarFilePath(playerProfileData.getMeta("avatar"));
        lblIcon.setIcon(FileAssets.getImageIcon(avatarFilePath, 30, 30));
        lblName.setText(playerProfileData.getLogin());
        boolean isOwnPlayer = isOwnPlayer(lobbyPlayer);
        btnKick.setEnabled(panLobby.isOwner() && (!isOwnPlayer));
    }
    private PanLobby panLobby;
    private LobbyPlayer lobbyPlayer;
    
    public static PlayerProfileData getLobbyPlayerProfile(LobbyPlayer lobbyPlayer){
        if(lobbyPlayer instanceof LobbyPlayer_Human){
            LobbyPlayer_Human lobbyPlayer_Human = (LobbyPlayer_Human) lobbyPlayer;
            return MasterserverClientUtil.getPlayerProfile(lobbyPlayer_Human.getPlayerId());
        }
        else if (lobbyPlayer instanceof LobbyPlayer_Bot) {
            LobbyPlayer_Bot lobbyPlayer_Bot = (LobbyPlayer_Bot) lobbyPlayer;
            HashMap<String, String> botMeta = new HashMap<>();
            botMeta.put("avatar", "bot");
            return new PlayerProfileData(-1, lobbyPlayer_Bot.getName(), botMeta);
        }
        return null;
    }
    
    public static boolean isOwnPlayer(LobbyPlayer lobbyPlayer){
        if(lobbyPlayer instanceof LobbyPlayer_Human){
            LobbyPlayer_Human lobbyPlayer_Human = (LobbyPlayer_Human) lobbyPlayer;
            return (MasterserverClientUtil.getPlayerId() == lobbyPlayer_Human.getPlayerId());
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblSeparator1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnKick = new javax.swing.JButton();

        setBackground(new java.awt.Color(30, 30, 30));

        lblIcon.setPreferredSize(new java.awt.Dimension(30, 30));

        lblSeparator1.setPreferredSize(new java.awt.Dimension(5, 30));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("???");
        lblName.setPreferredSize(new java.awt.Dimension(115, 30));

        btnKick.setText("X");
        btnKick.setPreferredSize(new java.awt.Dimension(40, 30));
        btnKick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnKick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKickActionPerformed
        panLobby.sendMessage(new Message_KickLobbyPlayer(lobbyPlayer.getLobbyPlayerID()));
    }//GEN-LAST:event_btnKickActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKick;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeparator1;
    // End of variables declaration//GEN-END:variables
}
