/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.applications.master.client.launcher.panels;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

import amara.applications.ingame.maps.MMOMaps;
import amara.applications.master.client.MasterserverClientUtil;
import amara.applications.master.client.launcher.buttons.*;
import amara.applications.master.network.messages.Message_CreateLobby;
import amara.applications.master.network.messages.Message_JoinMMOMap;
import amara.applications.master.network.messages.objects.GameSelectionPlayerData;
import amara.libraries.network.NetworkClient;
import com.jme3.network.Message;

/**
 *
 * @author Carl
 */
public class PanSelectGameMode extends JPanel {

    public PanSelectGameMode() {
        initComponents();
        JComponent btnCreateLobby = ButtonUtil.addImageBackgroundButton(panContainer_btnCreateLobby, new DefaultButtonBuilder("default_150x50", "Create Lobby"));
        btnCreateLobby.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent evt) {
                super.mouseClicked(evt);
                createLobby();
            }
        });
        for (String mmoMapName : MMOMaps.MAP_NAMES) {
            cbxMMOMapName.addItem(mmoMapName);
        }
        JComponent btnJoinMMOMap = ButtonUtil.addImageBackgroundButton(panContainer_btnJoinMMOMap, new DefaultButtonBuilder("default_150x50", "Join MMO Map"));
        btnJoinMMOMap.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent evt) {
                super.mouseClicked(evt);
                joinMMOMap();
            }
        });
    }

    private void createLobby() {
        sendMessage(new Message_CreateLobby());
    }

    private void joinMMOMap() {
        String mapName = (String) cbxMMOMapName.getSelectedItem();
        GameSelectionPlayerData gameSelectionPlayerData = new GameSelectionPlayerData(17, null);
        sendMessage(new Message_JoinMMOMap(mapName, gameSelectionPlayerData));
    }

    private void sendMessage(Message message) {
        NetworkClient networkClient = MasterserverClientUtil.getNetworkClient();
        networkClient.sendMessage(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContainer_btnCreateLobby = new javax.swing.JPanel();
        panContainer_btnJoinMMOMap = new javax.swing.JPanel();
        cbxMMOMapName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(30, 30, 30));

        javax.swing.GroupLayout panContainer_btnCreateLobbyLayout = new javax.swing.GroupLayout(panContainer_btnCreateLobby);
        panContainer_btnCreateLobby.setLayout(panContainer_btnCreateLobbyLayout);
        panContainer_btnCreateLobbyLayout.setHorizontalGroup(
            panContainer_btnCreateLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panContainer_btnCreateLobbyLayout.setVerticalGroup(
            panContainer_btnCreateLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panContainer_btnJoinMMOMapLayout = new javax.swing.GroupLayout(panContainer_btnJoinMMOMap);
        panContainer_btnJoinMMOMap.setLayout(panContainer_btnJoinMMOMapLayout);
        panContainer_btnJoinMMOMapLayout.setHorizontalGroup(
            panContainer_btnJoinMMOMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panContainer_btnJoinMMOMapLayout.setVerticalGroup(
            panContainer_btnJoinMMOMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MMO Map:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Team Game:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxMMOMapName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(panContainer_btnCreateLobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panContainer_btnJoinMMOMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 824, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContainer_btnCreateLobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMMOMapName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContainer_btnJoinMMOMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxMMOMapName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panContainer_btnCreateLobby;
    private javax.swing.JPanel panContainer_btnJoinMMOMap;
    // End of variables declaration//GEN-END:variables
}
