/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.launcher.client;

import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import amara.engine.network.exceptions.ServerConnectionTimeoutException;
import amara.launcher.FrameUtil;
import amara.launcher.client.panels.PanError;

/**
 *
 * @author Carl
 */
public class ErrorDialog extends javax.swing.JDialog{

    public ErrorDialog(Frame parent, Exception exception){
        super(parent);
        initComponents();
        panContainer.add(new PanError(exception));
        FrameUtil.initDialogSpecials(this);
        FrameUtil.centerFrame(this);
    }
    
    public static void show(Exception exception){
        final MainFrame mainFrame = MainFrame.getInstance();
        mainFrame.setEnabled(false);
        ErrorDialog errorDialog = new ErrorDialog(mainFrame, exception);
        errorDialog.addWindowListener(new WindowAdapter(){

            @Override
            public void windowClosed(WindowEvent evt){
                super.windowClosed(evt);
                mainFrame.setEnabled(true);
                mainFrame.toFront();
            }
        });
        errorDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panContainer.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        FrameUtil.initProgramProperties();
        ErrorDialog dialog = new ErrorDialog(null, new ServerConnectionTimeoutException("127.0.0.1", 42));
        dialog.addWindowListener(new java.awt.event.WindowAdapter(){
            
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panContainer;
    // End of variables declaration//GEN-END:variables
}
