/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panPlay.java
 *
 * Created on 02.08.2012, 23:56:34
 */
package amara.launcher.client.panels;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import amara.Util;

/**
 *
 * @author Carl
 */
public class PanHome extends javax.swing.JPanel{

    public PanHome(){
        initComponents();
        //loadNews();
        lblNewsTitle.setVisible(false);
    }
    
    /*private void loadNews(){
        MasterserverNewsRequest newsRequest = new MasterserverNewsRequest(3);
        newsRequest.send();
        Post[] posts = newsRequest.getPosts();
        for(int i=0;i<posts.length;i++){
            JPanel panPost = createNewsPanel(posts[i]);
            panNews.add(panPost);
        }
    }
    
    private JPanel createNewsPanel(Post post){
        JPanel panPost = new JPanel(new GridLayout(2, 1));
        panPost.setBackground(new Color(0, 0, 0));
        panPost.setBorder(new LineBorder(Color.WHITE));
        JLabel lblTitle = new JLabel(post.getTitle(), JLabel.CENTER);
        lblTitle.setFont(lblTitle.getFont().deriveFont(Font.BOLD, 12));
        lblTitle.setForeground(Color.WHITE);
        panPost.add(lblTitle);
        JLabel lblDate = new JLabel(Util.getFormattedDate(post.getDate()), JLabel.CENTER);
        lblDate.setForeground(Color.WHITE);
        panPost.add(lblDate);
        return panPost;
    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrHostOrConnect = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panNews = new javax.swing.JPanel();
        lblNewsTitle = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(30, 30, 30));

        panNews.setOpaque(false);
        panNews.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        lblNewsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblNewsTitle.setText("News:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panNews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNewsTitle)
                        .addGap(0, 597, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(lblNewsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panNews, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrHostOrConnect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblNewsTitle;
    private javax.swing.JPanel panNews;
    // End of variables declaration//GEN-END:variables
}
