/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panPlay.java
 *
 * Created on 02.08.2012, 23:56:34
 */
package amara.launcher.client.panels;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseMotionListener;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import amara.Util;
import amara.engine.applications.masterserver.server.protocol.*;
import amara.launcher.FrameUtil;
import amara.launcher.client.MainFrame;
import amara.launcher.client.MasterserverClientUtil;
import amara.launcher.client.comboboxes.ComboboxModel_OwnedCharacters;

/**
 *
 * @author Carl
 */
public class PanItems extends javax.swing.JPanel{

    public PanItems(){
        initComponents();
        loadItems();
        cbxCharacters.setModel(new ComboboxModel_OwnedCharacters(MasterserverClientUtil.getOwnedCharacters()));
        loadInventory();
    }
    private final int dragItemSize = 55;
    private HashMap<Item, ImageIcon> itemIcons;
    private ImageIcon itemIcon_None = Util.getResourceImageIcon("/Interface/hud/items/none.png", dragItemSize, dragItemSize);
    private JLabel lblInvetoryItems[] = new JLabel[6];
    private int[] inventoryItemIDs = new int[6];
    private JLabel lblDragItem;
    
    private void loadItems(){
        OwnedItem[] ownedItems = MasterserverClientUtil.getOwnedItems();
        itemIcons = new HashMap<Item, ImageIcon>(ownedItems.length);
        int padding = 2;
        int y = padding;
        for(final OwnedItem ownedItem : ownedItems){
            PanItems_OwnedItem panItem = new PanItems_OwnedItem(ownedItem);
            panItem.setLocation(padding, y);
            panItem.setSize(320, 60);
            panelItems.add(panItem);
            enableDragAndDrop(panItem, ownedItem.getItem());
            y += (60 + padding);
        }
        panelItems.setPreferredSize(new Dimension(320 + (2 * padding) + 18, y));
    }
    
    private void loadInventory(){
        int padding = 1;
        int x = padding;
        int y = padding;
        for(int i=0;i<6;i++){
            JLabel lblItem = new JLabel(itemIcon_None);
            lblItem.setLocation(x, y);
            lblItem.setSize(dragItemSize, dragItemSize);
            lblItem.setCursor(new Cursor(Cursor.HAND_CURSOR));
            panInventory.add(lblItem);
            lblInvetoryItems[i] = lblItem;
            x += (dragItemSize + padding);
            if(i == 2){
                x = padding;
                y += (dragItemSize + padding);
            }
        }
        lblDragItem = new JLabel();
        lblDragItem.setSize(dragItemSize, dragItemSize);
    }
    
    private void enableDragAndDrop(JComponent component, Item item){
        component.addMouseListener(new ItemDragAdapter(component, item));
        component.addMouseMotionListener(new ItemDropAdapter(component));
    }
    
    private void disableDragAndDrop(JComponent component){
        for(MouseListener mouseListener : component.getMouseListeners()){
            if(mouseListener instanceof ItemDragAdapter){
                component.removeMouseListener(mouseListener);
            }
        }
        for(MouseMotionListener mouseMotionListener : component.getMouseMotionListeners()){
            if(mouseMotionListener instanceof ItemDropAdapter){
                component.removeMouseMotionListener(mouseMotionListener);
            }
        }
    }
    
    private ImageIcon getItemIcon(Item item){
        ImageIcon icon = itemIcons.get(item);
        if(icon == null){
            icon = Util.getResourceImageIcon("/Interface/hud/items/" + item.getName() + ".png", dragItemSize, dragItemSize);
        }
        return icon;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrHostOrConnect = new javax.swing.ButtonGroup();
        scrollpanelItems = new javax.swing.JScrollPane();
        panelItems = new javax.swing.JPanel();
        cbxCharacters = new javax.swing.JComboBox();
        panInventory = new javax.swing.JPanel();

        setBackground(new java.awt.Color(30, 30, 30));

        scrollpanelItems.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpanelItems.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelItems.setPreferredSize(new java.awt.Dimension(324, 260));

        javax.swing.GroupLayout panelItemsLayout = new javax.swing.GroupLayout(panelItems);
        panelItems.setLayout(panelItemsLayout);
        panelItemsLayout.setHorizontalGroup(
            panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        panelItemsLayout.setVerticalGroup(
            panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        scrollpanelItems.setViewportView(panelItems);

        panInventory.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panInventoryLayout = new javax.swing.GroupLayout(panInventory);
        panInventory.setLayout(panInventoryLayout);
        panInventoryLayout.setHorizontalGroup(
            panInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        panInventoryLayout.setVerticalGroup(
            panInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanelItems, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxCharacters, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpanelItems)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private class ItemDragAdapter extends MouseAdapter{

        public ItemDragAdapter(JComponent sourceComponent, Item item){
            this.sourceComponent = sourceComponent;
            this.item = item;
            for(int i=0;i<lblInvetoryItems.length;i++){
                if(sourceComponent == lblInvetoryItems[i]){
                    inventorySourceIndex = i;
                    break;
                }
            }
        }
        private JComponent sourceComponent;
        private Item item;
        private int inventorySourceIndex = -1;

        @Override
        public void mousePressed(MouseEvent evt){
            super.mousePressed(evt);
            lblDragItem.setIcon(getItemIcon(item));
            MainFrame.getInstance().add(lblDragItem, 0);
        }

        @Override
        public void mouseReleased(MouseEvent evt){
            super.mouseReleased(evt);
            if(inventorySourceIndex != -1){
                inventoryItemIDs[inventorySourceIndex] = 0;
                lblInvetoryItems[inventorySourceIndex].setIcon(itemIcon_None);
                disableDragAndDrop(lblInvetoryItems[inventorySourceIndex]);
            }
            Point inventoryLocationInFrame = FrameUtil.getLocationIn(panInventory, MainFrame.getInstance().getContentPane());
            double mouseX = (lblDragItem.getX() + (lblDragItem.getWidth() / 2));
            double mouseY = (lblDragItem.getY() + (lblDragItem.getHeight() / 2));
            if((mouseX >= inventoryLocationInFrame.getX()) && (mouseX < (inventoryLocationInFrame.getX() + panInventory.getWidth()))
            && (mouseY >= inventoryLocationInFrame.getY()) && (mouseY < (inventoryLocationInFrame.getY() + panInventory.getHeight()))){
                double xPortion = ((mouseX - inventoryLocationInFrame.getX()) / panInventory.getWidth());
                double yPortion = ((mouseY - inventoryLocationInFrame.getY()) / panInventory.getHeight());
                int itemIndex = (int) (xPortion * 3);
                if(yPortion >= 0.5){
                    itemIndex += 3;
                }
                inventoryItemIDs[itemIndex] = item.getID();
                lblInvetoryItems[itemIndex].setIcon(getItemIcon(item));
                enableDragAndDrop(lblInvetoryItems[itemIndex], item);
            }
            MainFrame.getInstance().remove(lblDragItem);
            MainFrame.getInstance().repaint();
        }
    }
    
    private class ItemDropAdapter extends MouseMotionAdapter{

        public ItemDropAdapter(JComponent sourceComponent){
            this.sourceComponent = sourceComponent;
        }
        private JComponent sourceComponent;
        
        @Override
        public void mouseDragged(MouseEvent evt){
            super.mouseDragged(evt);
            Point locationInFrame = FrameUtil.getLocationIn(sourceComponent, MainFrame.getInstance().getContentPane());
            int x = (int) (locationInFrame.getX() + evt.getX() - (lblDragItem.getWidth() / 2));
            int y = (int) (locationInFrame.getY() + evt.getY() - (lblDragItem.getHeight() / 2));
            lblDragItem.setLocation(x, y);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrHostOrConnect;
    private javax.swing.JComboBox cbxCharacters;
    private javax.swing.JPanel panInventory;
    private javax.swing.JPanel panelItems;
    private javax.swing.JScrollPane scrollpanelItems;
    // End of variables declaration//GEN-END:variables
}
