/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.launcher.client.panels;

import amara.Util;
import amara.game.games.PlayerData;

/**
 *
 * @author Carl
 */
public class PanPlay_Player extends javax.swing.JPanel{

    public PanPlay_Player(PanPlay panPlay){
        this.panPlay = panPlay;
        initComponents();
    }
    private PanPlay panPlay;
    private LobbyPlayer lobbyPlayer;
    
    public void setPlayer(LobbyPlayer lobbyPlayer){
        this.lobbyPlayer = lobbyPlayer;
        update();
    }
    
    private void update(){
        String avatarResourcePath = PanAvatarSelection.getAvatarResourcePath(lobbyPlayer.getPlayerProfileData().getMeta("avatar"));
        lblIcon.setIcon(Util.getResourceImageIcon(avatarResourcePath, 30, 30));
        lblName.setText(lobbyPlayer.getPlayerProfileData().getLogin());
        cbxPlayerEntityTemplate.setSelectedItem(lobbyPlayer.getPlayerData().getUnitTemplate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblSeparator1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        cbxPlayerEntityTemplate = new javax.swing.JComboBox();
        btnRemove = new javax.swing.JButton();

        setBackground(new java.awt.Color(30, 30, 30));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        lblIcon.setPreferredSize(new java.awt.Dimension(30, 30));
        add(lblIcon);

        lblSeparator1.setText("jLabel1");
        lblSeparator1.setPreferredSize(new java.awt.Dimension(5, 30));
        add(lblSeparator1);

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("???");
        lblName.setPreferredSize(new java.awt.Dimension(115, 30));
        add(lblName);

        cbxPlayerEntityTemplate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "minion", "wizard", "robot", "jaime", "soldier", "steve" }));
        cbxPlayerEntityTemplate.setPreferredSize(new java.awt.Dimension(110, 30));
        cbxPlayerEntityTemplate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPlayerEntityTemplateItemStateChanged(evt);
            }
        });
        add(cbxPlayerEntityTemplate);

        btnRemove.setText("X");
        btnRemove.setPreferredSize(new java.awt.Dimension(40, 30));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPlayerEntityTemplateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPlayerEntityTemplateItemStateChanged
        String entityTemplate = cbxPlayerEntityTemplate.getSelectedItem().toString();
        lobbyPlayer.setPlayerData(new PlayerData(lobbyPlayer.getPlayerProfileData().getID(), entityTemplate));
    }//GEN-LAST:event_cbxPlayerEntityTemplateItemStateChanged

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        panPlay.removePlayerFromLobby(lobbyPlayer);
    }//GEN-LAST:event_btnRemoveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox cbxPlayerEntityTemplate;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeparator1;
    // End of variables declaration//GEN-END:variables
}
