/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.launcher.client.panels;

import java.awt.event.ItemEvent;
import amara.Util;
import amara.engine.applications.masterserver.server.network.messages.*;
import amara.engine.applications.masterserver.server.protocol.*;
import amara.launcher.client.MainFrame;

/**
 *
 * @author Carl
 */
public class PanLobby_Player extends javax.swing.JPanel{

    public PanLobby_Player(PanLobby panLobby, LobbyPlayer lobbyPlayer){
        initComponents();
        this.panLobby = panLobby;
        this.lobbyPlayer = lobbyPlayer;
        PlayerProfileData playerProfileData = MainFrame.getInstance().getPlayerProfile(lobbyPlayer.getID());
        String avatarResourcePath = PanAvatarSelection.getAvatarResourcePath(playerProfileData.getMeta("avatar"));
        lblIcon.setIcon(Util.getResourceImageIcon(avatarResourcePath, 30, 30));
        lblName.setText(playerProfileData.getLogin());
        cbxUnitTemplate.setSelectedItem(lobbyPlayer.getPlayerData().getUnitTemplate());
        boolean isOwnPlayer = (MainFrame.getInstance().getPlayerID() == lobbyPlayer.getID());
        cbxUnitTemplate.setEnabled(isOwnPlayer);
        btnKick.setEnabled(panLobby.isOwner() && (!isOwnPlayer));
    }
    private PanLobby panLobby;
    private LobbyPlayer lobbyPlayer;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblSeparator1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        cbxUnitTemplate = new javax.swing.JComboBox();
        btnKick = new javax.swing.JButton();

        setBackground(new java.awt.Color(30, 30, 30));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        lblIcon.setPreferredSize(new java.awt.Dimension(30, 30));
        add(lblIcon);

        lblSeparator1.setText("jLabel1");
        lblSeparator1.setPreferredSize(new java.awt.Dimension(5, 30));
        add(lblSeparator1);

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("???");
        lblName.setPreferredSize(new java.awt.Dimension(115, 30));
        add(lblName);

        cbxUnitTemplate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "minion", "wizard", "robot", "jaime", "soldier", "steve" }));
        cbxUnitTemplate.setPreferredSize(new java.awt.Dimension(110, 30));
        cbxUnitTemplate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxUnitTemplateItemStateChanged(evt);
            }
        });
        add(cbxUnitTemplate);

        btnKick.setText("X");
        btnKick.setPreferredSize(new java.awt.Dimension(40, 30));
        btnKick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKickActionPerformed(evt);
            }
        });
        add(btnKick);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxUnitTemplateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxUnitTemplateItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            String unitTemplate = cbxUnitTemplate.getSelectedItem().toString();
            if(!unitTemplate.equals(lobbyPlayer.getPlayerData().getUnitTemplate())){
                panLobby.sendMessage(new Message_SetLobbyPlayerData(new LobbyPlayerData(unitTemplate)));
            }
        }
    }//GEN-LAST:event_cbxUnitTemplateItemStateChanged

    private void btnKickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKickActionPerformed
        panLobby.sendMessage(new Message_KickLobbyPlayer(lobbyPlayer.getID()));
    }//GEN-LAST:event_btnKickActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKick;
    private javax.swing.JComboBox cbxUnitTemplate;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeparator1;
    // End of variables declaration//GEN-END:variables
}
