/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.launcher.client.panels;

import javax.swing.JPanel;

/**
 *
 * @author Carl
 */
public class PanMainMenu extends javax.swing.JPanel{

    public PanMainMenu(){
        initComponents();
        initializePanels();
    }
    private PanProfile panProfile;
    
    private void initializePanels(){
        panHeaderContainer.add(new PanHeader());
        addPanelTab("Home", new PanHome());
        panProfile = new PanProfile();
        addPanelTab("Profile", panProfile);
        addPanelTab("Play", new PanPlay());
        addPanelTab("Settings", new PanSettings());
        addPanelTab("Thanks", new PanThanks());
        addPanelTab("Info", new PanInfo());
    }
    
    private void addPanelTab(String title, JPanel panel){
        tpaneContainer.add(title, panel);
    }
    
    public void setSelectedTab(int tabIndex){
        tpaneContainer.setSelectedIndex(tabIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panHeaderContainer = new javax.swing.JPanel();
        tpaneContainer = new javax.swing.JTabbedPane();

        panHeaderContainer.setLayout(new java.awt.GridLayout(1, 0));

        tpaneContainer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpaneContainerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpaneContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addComponent(panHeaderContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panHeaderContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpaneContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tpaneContainerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpaneContainerStateChanged
        if(tpaneContainer.getSelectedComponent() == panProfile){
            panProfile.resetToOwnProfile();
        }
    }//GEN-LAST:event_tpaneContainerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panHeaderContainer;
    private javax.swing.JTabbedPane tpaneContainer;
    // End of variables declaration//GEN-END:variables
}
