/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.launcher.client.panels;

import javax.swing.JPanel;
import amara.engine.network.NetworkClient;
import amara.launcher.client.MainFrame;
import amara.launcher.client.network.backends.*;

/**
 *
 * @author Carl
 */
public class PanPlay extends javax.swing.JPanel{

    public PanPlay(PanMainMenu panMainMenu){
        initComponents();
        this.panMainMenu = panMainMenu;
        panCreateLobby = new PanCreateLobby();
        panLobby = new PanLobby(this);
        displayCreatePanel();
        NetworkClient networkClient = MainFrame.getInstance().getNetworkClient();
        networkClient.addMessageBackend(new UpdateLobbyBackend(this));
        networkClient.addMessageBackend(new ClosedLobbyBackend(this));
    }
    private PanMainMenu panMainMenu;
    private PanCreateLobby panCreateLobby;
    private PanLobby panLobby;
    
    public void displayCreatePanel(){
        setDisplayedPanel(panCreateLobby);
    }
    
    public void displayLobbyPanel(){
        setDisplayedPanel(panLobby);
    }
    
    private void setDisplayedPanel(JPanel panel){
        removeAll();
        add(panel);
        updateUI();
    }

    public PanCreateLobby getPanCreateLobby(){
        return panCreateLobby;
    }

    public PanLobby getPanLobby(){
        return panLobby;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
