/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panPlay.java
 *
 * Created on 02.08.2012, 23:56:34
 */
package amara.launcher.client.panels;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;
import amara.Util;
import amara.engine.network.NetworkClient;
import amara.engine.network.messages.protocol.Message_EditUserMeta;
import amara.launcher.FrameUtil;
import amara.launcher.client.MainFrame;
import amara.launcher.client.protocol.PlayerProfileData;

/**
 *
 * @author Carl
 */
public class PanProfile extends javax.swing.JPanel{

    public PanProfile(){
        initComponents();
        btnAvatar.setIcon(Util.getResourceImageIcon("/Interface/client/unknown.jpg", 100, 100));
        lblSearchLoader.setIcon(new ImageIcon(Util.getResourceURL("/Interface/client/loaders/user_search.gif")));
        lblSearchLoader.setVisible(false);
    }
    private boolean isOwnProfile;
    private boolean isSearchLoginFieldEmpty = true;
    private PanAvatarSelection panAvatarSelection;
    
    public void resetToOwnProfile(){
        txtSearchLogin.setText("");
        txtSearchLoginFocusLost(null);
        loadPlayerProfile(MainFrame.getInstance().getLogin());
    }
    
    private void loadPlayerProfile(final String login){
        new Thread(new Runnable(){

            public void run(){
                lblSearchLoader.setVisible(true);
                PlayerProfileData player = MainFrame.getInstance().getPlayerProfile(login);
                lblSearchLoader.setVisible(false);
                if(player != null){
                    showPlayerProfile(player);
                }
                else{
                    FrameUtil.showMessageDialog(PanProfile.this, "Player '" + login + "' wasn't found.", FrameUtil.MessageType.ERROR);
                }
            }
        }).start();
    }
    
    private void showPlayerProfile(PlayerProfileData player){
        lblProfileTitle.setText("Profile of " + player.getLogin());
        setAvatarIcon(player.getMeta("avatar"));
        lblUserData_ID.setText("" + player.getID());
        //lblUserData_RegistrationDate.setText(Util.getFormattedDate(player.getRegistrationDate()));
        isOwnProfile = player.getLogin().equals(MainFrame.getInstance().getLogin());
        if(isOwnProfile){
            btnAvatar.setCursor(new Cursor(Cursor.HAND_CURSOR));
            //lblUserData_EMail.setText(player.getEMail());
        }
        else{
            btnAvatar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            lblUserData_EMail.setText("?");
        }
    }
    
    public void changeAvatar(String avatar){
        NetworkClient networkClient = MainFrame.getInstance().getNetworkClient();
        networkClient.sendMessage(new Message_EditUserMeta("avatar", avatar));
        setAvatarIcon(avatar);
        panAvatarSelection.setVisible(false);
        txtSearchLogin.setEnabled(true);
    }
    
    private void setAvatarIcon(String avatar){
        btnAvatar.setIcon(Util.getResourceImageIcon(PanAvatarSelection.getAvatarResourcePath(avatar), btnAvatar.getWidth(), btnAvatar.getHeight()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrHostOrConnect = new javax.swing.ButtonGroup();
        panBox = new javax.swing.JPanel();
        lblProfileTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panUserData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUserData_ID = new javax.swing.JLabel();
        lblUserData_EMail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUserData_RegistrationDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchLogin = new javax.swing.JTextField();
        lblSearchLoader = new javax.swing.JLabel();
        btnAvatar = new javax.swing.JButton();

        panBox.setBackground(new java.awt.Color(30, 30, 30));

        lblProfileTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProfileTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblProfileTitle.setText("Profile of ?");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage, Sausage.</html>");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        panUserData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        panUserData.setOpaque(false);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        lblUserData_ID.setForeground(new java.awt.Color(255, 255, 255));
        lblUserData_ID.setText("?");

        lblUserData_EMail.setForeground(new java.awt.Color(255, 255, 255));
        lblUserData_EMail.setText("?");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-Mail:");

        lblUserData_RegistrationDate.setForeground(new java.awt.Color(255, 255, 255));
        lblUserData_RegistrationDate.setText("?");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Regist.:");

        javax.swing.GroupLayout panUserDataLayout = new javax.swing.GroupLayout(panUserData);
        panUserData.setLayout(panUserDataLayout);
        panUserDataLayout.setHorizontalGroup(
            panUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUserDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panUserDataLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUserData_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserDataLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUserData_EMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panUserDataLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUserData_RegistrationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panUserDataLayout.setVerticalGroup(
            panUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUserDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserData_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserData_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserData_RegistrationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtSearchLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchLoginFocusLost(evt);
            }
        });
        txtSearchLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchLoginKeyPressed(evt);
            }
        });

        btnAvatar.setContentAreaFilled(false);
        btnAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAvatarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAvatarMouseExited(evt);
            }
        });
        btnAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvatarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBoxLayout = new javax.swing.GroupLayout(panBox);
        panBox.setLayout(panBoxLayout);
        panBoxLayout.setHorizontalGroup(
            panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBoxLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panBoxLayout.createSequentialGroup()
                        .addComponent(lblProfileTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panUserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panBoxLayout.createSequentialGroup()
                        .addComponent(lblSearchLoader, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panBoxLayout.setVerticalGroup(
            panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBoxLayout.createSequentialGroup()
                        .addComponent(btnAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panBoxLayout.createSequentialGroup()
                        .addGroup(panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProfileTitle)
                            .addComponent(lblSearchLoader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearchLogin, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panUserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchLoginFocusGained
        if(isSearchLoginFieldEmpty){
            txtSearchLogin.setText("");
            txtSearchLogin.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSearchLoginFocusGained

    private void txtSearchLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchLoginFocusLost
        isSearchLoginFieldEmpty = txtSearchLogin.getText().isEmpty();
        if(isSearchLoginFieldEmpty){
            txtSearchLogin.setText("Search Player");
            txtSearchLogin.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtSearchLoginFocusLost

    private void txtSearchLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchLoginKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String login = txtSearchLogin.getText();
            loadPlayerProfile(login);
        }
    }//GEN-LAST:event_txtSearchLoginKeyPressed

    private void btnAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatarActionPerformed
        if(isOwnProfile){
            if(panAvatarSelection == null){
                panAvatarSelection = new PanAvatarSelection(this);
                panAvatarSelection.setLocation(panBox.getX() + btnAvatar.getX(), panBox.getY() + btnAvatar.getY());
                panAvatarSelection.setSize(352, 212);
                add(panAvatarSelection, 0);
            }
            btnAvatar.setIcon(null);
            txtSearchLogin.setEnabled(false);
            panAvatarSelection.setVisible(true);
            updateUI();
        }
    }//GEN-LAST:event_btnAvatarActionPerformed

    private void btnAvatarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvatarMouseEntered
        if(isOwnProfile){
            btnAvatar.setBorder(new LineBorder(Color.WHITE));
        }
    }//GEN-LAST:event_btnAvatarMouseEntered

    private void btnAvatarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvatarMouseExited
        if(isOwnProfile){
            btnAvatar.setBorder(null);
        }
    }//GEN-LAST:event_btnAvatarMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrHostOrConnect;
    private javax.swing.JButton btnAvatar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblProfileTitle;
    private javax.swing.JLabel lblSearchLoader;
    private javax.swing.JLabel lblUserData_EMail;
    private javax.swing.JLabel lblUserData_ID;
    private javax.swing.JLabel lblUserData_RegistrationDate;
    private javax.swing.JPanel panBox;
    private javax.swing.JPanel panUserData;
    private javax.swing.JTextField txtSearchLogin;
    // End of variables declaration//GEN-END:variables
}
