package amara.applications.ingame.server.entitysystem.systems.effects;

import amara.applications.ingame.entitysystem.systems.aggro.*;
import amara.applications.ingame.entitysystem.systems.effects.*;
import amara.applications.ingame.entitysystem.systems.effects.aggro.*;
import amara.applications.ingame.entitysystem.systems.effects.audio.*;
import amara.applications.ingame.entitysystem.systems.effects.buffs.*;
import amara.applications.ingame.entitysystem.systems.effects.buffs.areas.*;
import amara.applications.ingame.entitysystem.systems.effects.buffs.stacks.*;
import amara.applications.ingame.entitysystem.systems.effects.crowdcontrol.*;
import amara.applications.ingame.entitysystem.systems.effects.damage.*;
import amara.applications.ingame.entitysystem.systems.effects.game.*;
import amara.applications.ingame.entitysystem.systems.effects.general.*;
import amara.applications.ingame.entitysystem.systems.effects.heal.*;
import amara.applications.ingame.entitysystem.systems.effects.movement.*;
import amara.applications.ingame.entitysystem.systems.effects.physics.*;
import amara.applications.ingame.entitysystem.systems.effects.players.*;
import amara.applications.ingame.entitysystem.systems.effects.popups.*;
import amara.applications.ingame.entitysystem.systems.effects.spawns.*;
import amara.applications.ingame.entitysystem.systems.effects.spells.*;
import amara.applications.ingame.entitysystem.systems.effects.triggers.*;
import amara.applications.ingame.entitysystem.systems.effects.units.*;
import amara.applications.ingame.entitysystem.systems.effects.vision.*;
import amara.applications.ingame.entitysystem.systems.effects.visuals.*;
import amara.applications.ingame.entitysystem.systems.specials.erika.*;
import amara.applications.ingame.entitysystem.systems.spells.casting.CastSpellQueueSystem;
import amara.applications.ingame.entitysystem.systems.units.*;
import amara.applications.ingame.server.entitysystem.systems.general.LoopSystem;
import amara.applications.ingame.shared.maps.Map;
import amara.libraries.entitysystem.EntityWorld;

public class ApplyEffectsLoopSystem extends LoopSystem {

    public ApplyEffectsLoopSystem(Map map, CastSpellQueueSystem castSpellQueueSystem) {
        calculateEffectImpactSystem = new CalculateEffectImpactSystem();
        add(calculateEffectImpactSystem);
        // Apply adding and removing effect triggers first, so they are directly considered at the other effect impacts
        add(new ApplyAddEffectTriggersSystem());
        add(new ApplyRemoveEffectTriggersSystem());
        add(new ApplyPlayCinematicSystem());
        add(new ApplyDrawTeamAggroSystem());
        add(new ApplySetAggroTargetSystem());
        add(new ApplyPlayAudioSystem());
        add(new ApplyStopAudioSystem());
        add(new ApplyRemoveBuffsSystem());
        add(new ApplyRemoveBuffAreasSystem());
        add(new ApplyAddBuffsSystem());
        add(new ApplyAddBuffAreasSystem());
        add(new ApplyAddStacksSystem());
        add(new ApplyClearStacksSystem());
        add(new ApplyAddBindableSystem());
        add(new ApplyAddBindingSystem());
        add(new ApplyAddKnockupableSystem());
        add(new ApplyAddKnockupSystem());
        add(new ApplyAddSilencableSystem());
        add(new ApplyAddSilenceSystem());
        add(new ApplyAddStunSystem());
        add(new ApplyAddStunnableSystem());
        add(new ApplyRemoveBindableSystem());
        add(new ApplyRemoveBindingSystem());
        add(new ApplyRemoveKnockupableSystem());
        add(new ApplyRemoveKnockupSystem());
        add(new ApplyRemoveSilencableSystem());
        add(new ApplyRemoveSilenceSystem());
        add(new ApplyRemoveStunnableSystem());
        add(new ApplyRemoveStunSystem());
        add(new ApplyAddTargetabilitySystem());
        add(new ApplyRemoveTargetabilitySystem());
        add(new ApplyAddVulnerabilitySystem());
        add(new ApplyRemoveVulnerabilitySystem());
        add(new ApplyPhysicalDamageSystem());
        add(new ApplyMagicDamageSystem());
        add(new ApplyHealSystem());
        add(new ApplyStopSystem());
        add(new ApplyMoveSystem());
        add(new ApplyTeleportSystem());
        add(new ApplyRelativeTeleportSystem());
        add(new ApplyActivateHitboxSystem());
        add(new ApplyAddCollisiongGroupsSystem());
        add(new ApplyAddIntersectionPushedSystem());
        add(new ApplyAddIntersectionPushesSystem());
        add(new ApplyDeactivateHitboxSystem());
        add(new ApplyRemoveCollisiongGroupsSystem());
        add(new ApplyRemoveIntersectionPushedSystem());
        add(new ApplyRemoveIntersectionPushesSystem());
        add(new ApplySetScaleSystem());
        add(new ApplySwapPositionsSystem());
        add(new ApplyDisplayPlayerAnnouncementsSystem());
        add(new ApplyAddPopupsSystem());
        add(new ApplyRemovePopupsSystem());
        add(new ApplySpawnsSystems());
        add(new ApplyAddAutoAttackSpellEffectsSystem());
        add(new ApplyAddSpellSpellEffectsSystem());
        add(new ApplyEnqueueSpellCastSystem(castSpellQueueSystem));
        add(new ApplyRemoveSpellEffectsSystem());
        add(new ApplyReplaceSpellsWithExistingSpellsSystem());
        add(new ApplyReplaceSpellsWithNewSpellsSystem());
        add(new ApplyResetCooldownSystem());
        add(new ApplyTriggerSpellEffectsSystem());
        add(new ApplyAddGoldSystem());
        add(new ApplyAddShieldSystem());
        add(new ApplyCancelActionsSystem());
        add(new ApplyDisableAutoAttackSystem());
        add(new ApplyDisableSpellsSystem());
        add(new ApplyEnableAutoAttackSystem());
        add(new ApplyEnableSpellsSystem());
        add(new ApplyLevelUpSystem());
        add(new ApplyRemoveAutoAggroSystem());
        add(new ApplyRespawnSystem(map));
        add(new ApplySetAsRespawnTransformSystem());
        add(new ApplySetAutoAggroSystem());
        add(new ApplyAddStealthSystem());
        add(new ApplyRemoveStealthSystem());
        add(new ApplyPlayAnimationsSystem());
        add(new ApplyStopAnimationsSystem());
        add(new ApplyAddComponentsSystem());
        add(new ApplyFinishObjectivesSystem());
        add(new ApplyRemoveComponentsSystem());
        add(new ApplyRemoveEntitySystem());
        add(new ApplyTriggerErikaPassivesSystem());
        add(new SetInCombatSystem());
        add(new DrawAggroOnDamageSystem());
        add(new ResetAggroTimerOnDamageSystem());
        add(new UpdateDamageHistorySystem());
        add(new TriggerDamageTakenSystem());
        add(new LifestealSystem());
        add(new SpellvampSystem());
        add(new RemoveAppliedEffectImpactsSystem());
    }
    private CalculateEffectImpactSystem calculateEffectImpactSystem;

    @Override
    protected boolean isFinished(EntityWorld entityWorld) {
        return !calculateEffectImpactSystem.hasApplicableEffectCastEntities(entityWorld);
    }
}
