/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package amara.libraries.applications.windowed.dialogs;

import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import amara.libraries.applications.windowed.FrameUtil;
import amara.libraries.applications.windowed.dialogs.panels.PanError;

/**
 *
 * @author Carl
 */
public class ErrorDialog extends javax.swing.JDialog{

    public ErrorDialog(Frame parent, String errorMessage){
        super(parent);
        initComponents();
        panContainer.add(new PanError(errorMessage));
        FrameUtil.initDialogSpecials(this);
        FrameUtil.centerFrame(this);
    }
    private static JFrame mainFrame;
    
    public static void setMainFrame(JFrame _mainFrame){
        mainFrame = _mainFrame;
    }
    
    public static ErrorDialog show(String errorMessage){
        if(mainFrame != null){
            mainFrame.setEnabled(false);
        }
        ErrorDialog errorDialog = new ErrorDialog(mainFrame, errorMessage);
        errorDialog.addWindowListener(new WindowAdapter(){

            @Override
            public void windowClosed(WindowEvent evt){
                super.windowClosed(evt);
                if(mainFrame != null){
                    mainFrame.setEnabled(true);
                    mainFrame.toFront();
                }
                else{
                    System.exit(0);
                }
            }
        });
        errorDialog.setVisible(true);
        return errorDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panContainer.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panContainer;
    // End of variables declaration//GEN-END:variables
}
