CREATE TABLE IF NOT EXISTS CHARACTERS(ID INTEGER  NOT NULL,NAME VARCHAR(1000) NOT NULL,TITLE VARCHAR(1000) DEFAULT '' NOT NULL, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS CHARACTERS_SKINS(ID INTEGER  NOT NULL,CHARACTERID INTEGER NOT NULL,NAME VARCHAR(1000) NOT NULL,TITLE VARCHAR(1000) DEFAULT '' NOT NULL, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS ITEMS(ID INTEGER  NOT NULL,NAME VARCHAR(1000) NOT NULL,TITLE VARCHAR(1000) NOT NULL, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS USERS(ID INTEGER  NOT NULL,LOGIN VARCHAR(1000) NOT NULL,PASSWORD VARCHAR(1000) NOT NULL,LAST_MODIFICATION_DATE BIGINT, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS USERS_CHARACTERS(ID INTEGER  NOT NULL,USERID INTEGER NOT NULL,CHARACTERID INTEGER NOT NULL,SKINID INTEGER NOT NULL,INVENTORY INTEGER ARRAY[6] NOT NULL, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS USERS_CHARACTERS_SKINS(ID INTEGER  NOT NULL,USERID INTEGER NOT NULL,SKINID INTEGER NOT NULL, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS USERS_ITEMS(ID INTEGER  NOT NULL,USERID INTEGER NOT NULL,ITEMID INTEGER NOT NULL,AMOUNT INTEGER NOT NULL, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS USERS_META(ID INTEGER  NOT NULL,USERID INTEGER NOT NULL,KEY VARCHAR(1000) NOT NULL,VALUE VARCHAR(1000) NOT NULL, PRIMARY KEY(ID));