DROP TABLE CHARACTERS;
DROP TABLE CHARACTERS_SKINS;
DROP TABLE ITEMS;
DROP TABLE USERS;
DROP TABLE USERS_CHARACTERS;
DROP TABLE USERS_CHARACTERS_SKINS;
DROP TABLE USERS_ITEMS;
DROP TABLE USERS_META;