TRUNCATE TABLE CHARACTERS;
TRUNCATE TABLE CHARACTERS_SKINS;
TRUNCATE TABLE ITEMS;
TRUNCATE TABLE USERS;
TRUNCATE TABLE USERS_CHARACTERS;
TRUNCATE TABLE USERS_CHARACTERS_SKINS;
TRUNCATE TABLE USERS_ITEMS;
TRUNCATE TABLE USERS_META;
TRUNCATE TABLE USERS_META_DEFAULTS;
TRUNCATE TABLE WEBSITE_SESSIONS;
INSERT INTO USERS(SECURE_ID,LOGIN,PASSWORD,EMAIL,IS_ACTIVATED,REGISTRATION_DATE,LAST_MODIFICATION_DATE) VALUES('01','destroflyer','O8uj4RrS6XDfl1dZm9WxrQ==','destroflyer@???.com',true,1453179279600,1453179279600);
INSERT INTO USERS(SECURE_ID,LOGIN,PASSWORD,EMAIL,IS_ACTIVATED,REGISTRATION_DATE,LAST_MODIFICATION_DATE) VALUES('23','Etherblood','dqtF9HdsGlygSdM0aYFN5A==','etherblood@???.com',true,1448311558666,1448311558666);
INSERT INTO USERS(SECURE_ID,LOGIN,PASSWORD,EMAIL,IS_ACTIVATED,REGISTRATION_DATE,LAST_MODIFICATION_DATE) VALUES('45','Icecold','2vIfz9Q2RLxyRRunM8iEcg==','icecold@???.com',true,1402059013712,1402059013712);
INSERT INTO USERS(SECURE_ID,LOGIN,PASSWORD,EMAIL,IS_ACTIVATED,REGISTRATION_DATE,LAST_MODIFICATION_DATE) VALUES('67','TeMMeZz','ML8/B9tx86NAv9PNx+ZRpw==','temmezz@???.com',true,1402271254508,1402271254508);
INSERT INTO USERS(SECURE_ID,LOGIN,PASSWORD,EMAIL,IS_ACTIVATED,REGISTRATION_DATE,LAST_MODIFICATION_DATE) VALUES('89','egoVidiTe','9FF0BcWcigXKKvTsUQ+I2w==','egovidite@???.com',true,1452493682579,1452493682579);
INSERT INTO USERS_META_DEFAULTS(KEY,VALUE) VALUES('avatar','jmonkeyengine');
INSERT INTO USERS_META_DEFAULTS(KEY,VALUE) VALUES('profile_text','');
INSERT INTO USERS_META(USERID,KEY,VALUE) VALUES(1,'avatar','ether_anna');
INSERT INTO USERS_META(USERID,KEY,VALUE) VALUES(2,'avatar','ether_amara');
INSERT INTO USERS_META(USERID,KEY,VALUE) VALUES(1,'profile_text','Woof.');
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('minion','Minion','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('wizard','Wizard','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('robot','Robot','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('jaime','Jaime','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('soldier','Soldier','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('steve','Steve','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('daydream','Daydream','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('oz','Oz','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('varus','Varus','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('nathalya','Nathalya','',false);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('ganfaul','Ganfaul',E'Deep in the Ioborin Forest, there once was an ancient tribe called Otaki. Although they didn’t interact much with the world outside their territories, the Otaki were highly feared due to their warlike rituals and dark magic. While the wizards in the nearby kingdom of Eastcliff studied the magic of light and experimented to enhance their magic with new artificial tools, the tribe prayed to the nature and the night. This lead to a great despise against the „barbaric tribe of the forest“ - The disgust and fear inside the kingdom grew and grew… until the young Andrion Farstride ascended Eastcliff’s throne. Driven by greed and conservative advisors, he eventually decided to attack the primitive tribe. But little did he and his army knew about the true power of its shamans: A giant war started and lasted for three nights and three days. The Otaki had no choice but to use their tribe’s forbidden techniques, granting them huge power… at the cost of losing a part of their humanity. They grew body parts of animals, lost their voice and became one with nature and some of its deepest forces. Using those spells, being outnumbered by a large amount, the Otaki took out most of King Andrions army before finally getting encircled and defeated. It became clear, that with only a few dozen of soldiers left, Eastcliff could not win another fight against such bestial creatures in the future - In fear of losing his authority, the king decided to annihilate the whole Otaki tribe: Prisoners, soldiers, the elders, women and their kids. On this day, only one tribal survived - A little baby, rescued by Trasimond, an old wizard among the royal army. He has been serving the throne since many years and was a close friend to Andrions father, King Bradley. Knowing, that the old king wouldn’t have approved this genocide, he decided to rescue the little child with gray hair, hide his origin and to teach him in the wizard academy of Eastcliff, Avaetora.\n\nWhile growing up, the child named Ganfaul learned the usage and ethics of Eastcliff’s white magic and to live in peace. Trasimond taught him everything he knew and the young boy absorbed every bit of arcane knowledge he could. At the age of 28, he already surpassed his mentor and became an official wizard serving the royal family. But something inside of Ganfaul was still seeking for power - Power in a form and shape he just couldn’t see in all those bright lectures and rulings of the wizards. He searched and searched… until the day that he discovered the hidden part of the academies library, guarded by two soldiers he had never seen before. Using a difficult and long-planned illusion spell, he could deceive the guards and secretly slip in the library. After hours of studying the chronicles of Eastcliff and all of its secrets, Ganfaul found what his soul was seeking for all those years: The history of the mighty Otaki tribe… a tribe, so powerful they bonded with the nature, obtaining unbelievable powers… HIS tribe! Memories he believed to be dreams, flashed before his eyes and after remembering what happened years ago, Ganfaul could not longer control himself. Screaming and igniting the library, it only took a short amount of time for someone to show up: It was Trasimond, the man who saved him and became his mentor. He noticed the tribal books in the hands of Ganfaul and tried to convince him to calm down, but without success. Being old and surpassed by his student since a long time, the wizard did not stand a chance against the raging Otaki, who slaughtered him and the guards in seconds. After opening his eyes again and realizing, what he had done, Ganfaul took the kept books and scripts of his tribe and left the academy in a trail of blood. He returned to the Ioborin Forest, swearing death to King Andrion and preparing the revival of his tribe. No one has ever seen him again or knows which of the old bestial powers Ganfaul was able to obtain - But the day that the last Otaki returns… there will be war.',true);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('kachujin','Kachujin','',true);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('maw','Maw','',true);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('erika','Erika',E'When talking about Eastcliff, people usually think of the majestic city, its great walls, bright streets and wealth. But where there is light, there is also shadow: The cities slums, far in the south. Gloomy streets, filled with dirt, sewage and criminals. A place, where only the toughest people could make a living… or those who already gave up. Only looking from day to day, life in Eastcliff’s dark corners isn’t easy. This was revealed to Erika Pinefall in a young age - Her parents abandoned her after the birth, knowing they could not afford to raise a child or offer her anything else besides hunger and pain. Growing up in an orphanage, Erika had no one to connect with… and no one to trust - The house’s rules were clear: The more orphans, the less to eat for everyone. It wasn’t uncommon for the children to expel newcomers. But the young girl managed to fight, survive and grow - Knowing she could never physically compete with the older boys or lurking thieves in the streets, she resorted to cunning, intelligent maneuvers and outranging her opponents. She mastered to defeat aggressors with arrow and bow before they could even reach her.\n\nAfter leaving the orphanage at the age of 19, Erika tried to escape her old life and to find work in the upper part of Eastcliff, but wherever she went, she was rejected harshly. No one wanted to deal with a dirty hiker from the slums. Although she never wanted to harm people again, Erika’s rough childhood and the steady rejection since her birth formed her into a criminal. In order to survive, she had no choice but to rob other thieves and finally even passers, mostly wealthy citizens at the borders of Eastcliff. Becoming known as the „Orphan Bandit“, Erika single-handedly managed to double the cities street patrols, but never got caught. Remaining in the shadows, she’s aiming her arrow to any nearby aggressor and doing everything necessary to survive.',true);
INSERT INTO CHARACTERS(NAME,TITLE,LORE,IS_PUBLIC) VALUES('maria','Maria','',true);
INSERT INTO CHARACTERS_SKINS(CHARACTERID,NAME,TITLE) VALUES(7,'fire','Firedream');
INSERT INTO CHARACTERS_SKINS(CHARACTERID,NAME,TITLE) VALUES(7,'nightmare','Nightmare');
INSERT INTO CHARACTERS_SKINS(CHARACTERID,NAME,TITLE) VALUES(7,'envy','Envy');
INSERT INTO CHARACTERS_SKINS(CHARACTERID,NAME,TITLE) VALUES(3,'definitely_not','Definitely Not Robot');
INSERT INTO CHARACTERS_SKINS(CHARACTERID,NAME,TITLE) VALUES(1,'gentleman','Gentleman Minion');
INSERT INTO CHARACTERS_SKINS(CHARACTERID,NAME,TITLE) VALUES(8,'oz_junior','Oz Junior');
INSERT INTO CHARACTERS_SKINS(CHARACTERID,NAME,TITLE) VALUES(7,'inuyasha','Inuyasha');
INSERT INTO CHARACTERS_SKINS(CHARACTERID,NAME,TITLE) VALUES(7,'amazoness','Amazoness Daydream');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,1,5,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,2,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,3,4,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,4,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,5,0, '{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,6,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,7,1,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,8,6,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,9,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,10,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,11,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,12,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,13,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,14,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(1,15,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,1,5,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,2,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,3,4,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,4,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,5,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,6,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,7,7,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,8,6,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,9,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,10,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,11,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,12,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,13,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,14,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(2,15,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(3,11,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(3,12,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(3,13,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(3,14,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(3,15,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(4,11,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(4,12,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(4,13,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(4,14,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(4,15,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(5,11,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(5,12,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(5,13,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(5,14,0,'{}');
INSERT INTO USERS_CHARACTERS(USERID,CHARACTERID,SKINID,INVENTORY) VALUES(5,15,0,'{}');
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(1,1);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(1,2);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(1,3);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(1,4);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(1,5);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(1,6);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(1,7);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(1,8);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(2,1);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(2,2);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(2,3);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(2,4);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(2,5);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(2,6);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(2,7);
INSERT INTO USERS_CHARACTERS_SKINS(USERID,SKINID) VALUES(2,8);